# Generated by Django 5.0.6 on 2024-05-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='제목없음', max_length=100)),
                ('parent', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
