# Generated by Django 5.0.6 on 2024-05-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notion',
            name='user',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
