# Generated by Django 5.0.6 on 2024-05-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0002_notion_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notion',
            name='url',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
