# Generated by Django 5.0.6 on 2024-05-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0003_notion_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='notion',
            name='content',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
