# Generated by Django 5.0.6 on 2024-05-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0004_notion_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notion',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
