# Generated by Django 5.0.6 on 2024-05-31 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0005_alter_notion_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notion',
            name='parent',
            field=models.CharField(default='range(0)', max_length=255),
        ),
    ]
