# Generated by Django 5.0.6 on 2024-05-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0009_alter_notion_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notion',
            name='parent',
            field=models.JSONField(default=''),
        ),
    ]
