# Generated by Django 5.0.6 on 2024-05-31 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0011_alter_notion_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notion',
            name='url',
        ),
        migrations.AlterField(
            model_name='notion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notion.notion'),
        ),
    ]
