# Generated by Django 5.0.6 on 2024-05-31 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0012_remove_notion_url_alter_notion_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notion',
            name='parent',
        ),
    ]
