# Generated by Django 5.0.6 on 2024-05-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0013_remove_notion_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='notion',
            name='parent',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notion',
            name='url',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
