# Generated by Django 5.0.6 on 2024-05-31 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0014_notion_parent_notion_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notion.notion'),
        ),
    ]
