# Generated by Django 5.0.6 on 2024-05-31 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0015_alter_notion_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='notion.notion'),
        ),
    ]
